from pathlib import Path
import subprocess

# =========================
# CONFIG
# =========================

FORMATS = {".mp4", ".mov", ".avi", ".mkv"}

# =========================
# FUNCTIONS
# =========================

def clean_path(raw: str) -> Path:
    raw = raw.strip().replace('"', "").replace("'", "")
    if raw.startswith("/") and len(raw) > 2 and raw[2] == "/":
        raw = f"{raw[1].upper()}:{raw[2:]}"
    return Path(raw)


def resolve_files(path: Path) -> list[Path]:
    """Returns all video files in a folder, or a single file."""
    if path.is_dir():
        return sorted([f for f in path.iterdir() if f.suffix.lower() in FORMATS])
    elif path.suffix.lower() in FORMATS:
        return [path]
    return []


def split(video_path: Path, output_folder: Path) -> bool:
    """
    Splits audio and video into a split/ subfolder inside output_folder.
    Returns True on success.
    """
    split_folder = output_folder / "split"
    split_folder.mkdir(parents=True, exist_ok=True)

    footage = split_folder / f"{video_path.stem}_footage.mp4"
    audio   = split_folder / f"{video_path.stem}_audio.mp3"

    ok_v = subprocess.run([
        "ffmpeg", "-i", str(video_path),
        "-an", "-c:v", "copy", "-y", str(footage)
    ], check=False).returncode == 0

    ok_a = subprocess.run([
        "ffmpeg", "-i", str(video_path),
        "-vn", "-q:a", "0", "-y", str(audio)
    ], check=False).returncode == 0

    if ok_v and ok_a:
        readme = split_folder / "README.txt"
        readme.write_text(
            f"Files generated by splitter — Nico Digitals Engine\n"
            f"Original raw footage: {video_path.name}\n\n"
            f"- {footage.name}: video without audio (direct copy, no reencoding)\n"
            f"- {audio.name}: audio without video (maximum quality)\n",
            encoding="utf-8"
        )
        print(f"   ✅ {footage.name}", flush=True)
        print(f"   ✅ {audio.name}", flush=True)
        print(f"   ✅ README.txt", flush=True)
        return True
    else:
        print("   ❌ Split failed.", flush=True)
        return False


# =========================
# MAIN LOOP
# =========================

if __name__ == "__main__":

    while True:

        print("\n==============================")
        print(" FFmpeg Video Splitter")
        print("==============================")

        raw_input = input("\nDrag a video or folder here, or type 'exit': ").strip()

        if raw_input.lower() == "exit":
            print("\n👋 Closing...")
            break

        path = clean_path(raw_input)

        if not path.exists():
            print(f"\n❌ Not found: {path}")
            continue

        files = resolve_files(path)

        if not files:
            print("\n❌ No compatible video files found.")
            continue

        if path.is_dir():
            print(f"\n📁 Folder detected — {len(files)} file(s) to process.", flush=True)

        for i, video_path in enumerate(files, start=1):
            if len(files) > 1:
                print(f"\n[{i}/{len(files)}]", flush=True)

            output_folder = video_path.parent / video_path.stem
            ok = split(video_path, output_folder)

            if ok:
                print(f"\n✅ Done.")
                print(f"📁 {output_folder / 'split'}")
